//! Deterministic PRNG — mulberry32 with Poisson sampling.
//!
//! Bit-identical to the TypeScript implementation in `apps/web/src/seed/prng.ts`.
//! Same seed produces the same sequence in both languages.

/// Seedable 32-bit PRNG using the mulberry32 algorithm.
pub struct Rng {
    state: u32,
}

impl Rng {
    pub fn new(seed: u32) -> Self {
        Self { state: seed }
    }

    /// Returns a float in [0, 1). Matches the TS `next()` function.
    #[allow(clippy::should_implement_trait)]
    pub fn next(&mut self) -> f64 {
        self.state = self.state.wrapping_add(0x6d2b79f5);
        let mut t = self.state;
        t = (t ^ (t >> 15)).wrapping_mul(t | 1);
        t ^= t.wrapping_add((t ^ (t >> 7)).wrapping_mul(t | 61));
        (t ^ (t >> 14)) as f64 / 4_294_967_296.0
    }

    /// Pick a random element from a slice.
    pub fn pick<'a, T>(&mut self, slice: &'a [T]) -> &'a T {
        let idx = (self.next() * slice.len() as f64) as usize;
        &slice[idx]
    }

    /// Pick from weighted choices. Each entry is `(value, weight)`.
    pub fn pick_weighted<'a, T>(&mut self, choices: &'a [(T, f64)]) -> &'a T {
        let total: f64 = choices.iter().map(|(_, w)| w).sum();
        let mut r = self.next() * total;
        for (v, w) in choices {
            r -= w;
            if r <= 0.0 {
                return v;
            }
        }
        &choices[choices.len() - 1].0
    }

    /// Random integer in [min, max] inclusive.
    pub fn rand_int(&mut self, min: i32, max: i32) -> i32 {
        let range = (max - min + 1) as f64;
        (self.next() * range) as i32 + min
    }

    /// Advance the state and return the raw u32. Used for
    /// deterministic id derivation (`uuid_from_rng`) — `next()`
    /// loses bits in the f64 conversion, but for byte-filling a
    /// UUID we want the full 32-bit advance.
    pub fn next_u32(&mut self) -> u32 {
        self.state = self.state.wrapping_add(0x6d2b79f5);
        let mut t = self.state;
        t = (t ^ (t >> 15)).wrapping_mul(t | 1);
        t ^= t.wrapping_add((t ^ (t >> 7)).wrapping_mul(t | 61));
        t ^ (t >> 14)
    }
}

/// Build a deterministic UUID-v4-shaped value from the engine's
/// seeded Rng. Critical for correctness-protocol property 5
/// (replays produce byte-identical output) — the default
/// `JobId::new()` / `StepId::new()` paths use `Uuid::new_v4()`,
/// which mints fresh non-deterministic IDs every run; engine
/// callers swap to `uuid_from_rng(rng)` so the id stream is
/// reproducible.
///
/// The result is a valid UUID v4 (version + variant bits set
/// per RFC 4122) so downstream consumers (postgres, the
/// frontend, audit-log replay) treat it indistinguishably from
/// a `Uuid::new_v4()`. Determinism is the only difference.
pub fn uuid_from_rng(rng: &mut Rng) -> uuid::Uuid {
    let mut bytes = [0u8; 16];
    for chunk in bytes.chunks_mut(4) {
        let v = rng.next_u32();
        chunk.copy_from_slice(&v.to_le_bytes());
    }
    // Set the v4 version + RFC 4122 variant bits.
    bytes[6] = (bytes[6] & 0x0F) | 0x40;
    bytes[8] = (bytes[8] & 0x3F) | 0x80;
    uuid::Uuid::from_bytes(bytes)
}

/// Poisson-distributed sample using Knuth's algorithm. Good for lambda < 30.
pub fn poisson_sample(rng: &mut Rng, lambda: f64) -> u32 {
    let l = (-lambda).exp();
    let mut k: u32 = 0;
    let mut p: f64 = 1.0;
    loop {
        k += 1;
        p *= rng.next();
        if p <= l {
            break;
        }
    }
    k - 1
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify the first 5 values from seed 0xcafebabe match the TS implementation.
    ///
    /// Generated by running:
    ///   bun -e "import { createRng } from './apps/web/src/seed/prng';
    ///     const rng = createRng(0xcafebabe);
    ///     for (let i = 0; i < 5; i++) console.log(rng.next());"
    #[test]
    fn mulberry32_matches_typescript() {
        let expected: [f64; 5] = [
            0.5782299907878041,
            0.9793111204635352,
            0.7408307811710984,
            0.2960183585528284,
            0.1459375221747905,
        ];
        let mut rng = Rng::new(0xcafebabe);
        for (i, &want) in expected.iter().enumerate() {
            let got = rng.next();
            assert!(
                (got - want).abs() < 1e-15,
                "value {i}: got {got}, want {want}"
            );
        }
    }

    #[test]
    fn different_seeds_differ() {
        let mut a = Rng::new(0xcafebabe);
        let mut b = Rng::new(0xdeadbeef);
        assert_ne!(a.next().to_bits(), b.next().to_bits());
    }

    #[test]
    fn pick_returns_element_from_slice() {
        let mut rng = Rng::new(42);
        let items = [1, 2, 3, 4, 5];
        let picked = *rng.pick(&items);
        assert!(items.contains(&picked));
    }

    #[test]
    fn rand_int_in_range() {
        let mut rng = Rng::new(42);
        for _ in 0..100 {
            let v = rng.rand_int(5, 10);
            assert!((5..=10).contains(&v), "out of range: {v}");
        }
    }

    #[test]
    fn poisson_sample_reasonable() {
        let mut rng = Rng::new(42);
        let mut sum = 0u32;
        let n = 1000;
        for _ in 0..n {
            sum += poisson_sample(&mut rng, 0.5);
        }
        let mean = sum as f64 / n as f64;
        // Lambda=0.5, expect mean near 0.5 with some tolerance.
        assert!(mean > 0.3 && mean < 0.7, "poisson mean: {mean}");
    }
}
