//! `boss-rebuild-all` — replay every per-service projection from
//! `audit_log` in one command.
//!
//! Order matters in exactly one place: `boss-catalog` upserts the
//! shared `parts` table as a side-effect of model replay, and
//! `boss-inventory` references `parts` via the
//! `purchase_order_lines.part_sku` FK. So catalog runs before
//! inventory. Everything else is independent.
//!
//! Every step holds its projection's advisory lock under a stable
//! per-service key (`boss_core::rebuild::lock_key`), so two rebuilds of
//! one projection never interleave: a `pg_advisory_xact_lock` held by
//! the rebuild's transaction for all but `event-facts`, which is windowed
//! by design and so holds a session lock (`pg_advisory_lock`) for its
//! whole run — the same lock its five-minute catch-up takes. Running the
//! steps in series,
//! not in parallel, keeps the wipe + replay phase visible to a single
//! observer. This said "each" while six steps took none (subject-kinds,
//! classes, subjects, campaigns, customers, event-facts; measured
//! 2026-09-28, backlog df6aedb4), and is true since backlog 8d5ac7c5 —
//! each of those has a test that it waits on a held key. A new `step!`
//! whose rebuilder takes no lock fails boss-testing's
//! `every_rebuild_step_takes_its_lock`, which names the step; a step
//! whose key is not its name is listed in that pin's `KEY_OF_STEP`
//! (backlog 1d7fb51e).
//!
//! What the lock does NOT do: no live writer takes it, and every step
//! reads `audit_log` only, so a live write whose fact still sits in
//! `event_outbox` would be wiped and never replayed. Each step that
//! wipes a projection the log feeds proves the log holds every
//! committed write first, under table locks in its own transaction, or
//! REFUSES, naming the count and the oldest write
//! (`boss_events::outbox::lock_and_assert_log_complete`, design
//! b046f510, backlog d6656496). Before each step this binary waits,
//! unlocked, up to `--drain-timeout` for the relay to catch up, so a
//! live run is refused only when the relay is truly behind. A run that
//! succeeds is correct; a step that would deadlock a live writer yields
//! its locks and retries rather than abort the write.
//!
//! What a live run COSTS: each wiping step holds SHARE on `event_outbox`
//! for its whole replay, which freezes EVERY outbox writer in the estate
//! until the step commits — every domain write, and the gateway's
//! synchronous passkey-elevation audit write with them, so an owner's
//! elevation hangs for the step's duration — and its ACCESS EXCLUSIVE
//! on the wiped tables blocks their READERS too (jobs and steps read
//! nothing while the jobs step replays). No step's replay time on a
//! production-sized log has been measured yet. So running this against
//! a live instance is an operator's decision, taken knowing writes stall
//! for as long as the longest step replays — not a routine repair.
//!
//! Exit code: 0 on full success, non-zero if any service fails.
//! Per-service stats dump as one structured tracing line each.

use std::path::PathBuf;
use std::time::Instant;

use anyhow::{Context, Result};
use clap::Parser;
use sqlx::postgres::PgPoolOptions;
use tracing::{error, info, warn};
use tracing_subscriber::EnvFilter;

#[derive(Parser, Debug)]
#[command(
    name = "boss-rebuild-all",
    about = "Rebuild every projection from audit_log in dependency order",
    version
)]
struct Cli {
    /// Postgres URL. Required — pass via --database-url or set
    /// DATABASE_URL in env (sqlx convention). No config-file
    /// probing; this is a destructive operation, spell it out.
    #[arg(long, env = "DATABASE_URL")]
    database_url: String,

    /// Skip a service. Repeatable. Mostly useful for one-offs:
    /// `--skip catalog` to keep asset_models intact while
    /// rebuilding everything else.
    #[arg(long = "skip")]
    skip: Vec<String>,

    /// Run only the named services. Repeatable. Inverse of
    /// `--skip` — every service NOT listed here is skipped.
    /// Useful when a single audit_log row was just written and the
    /// operator wants to project only that one service (e.g. the
    /// quickstart bootstrap-admin → `--only people`).
    #[arg(long = "only")]
    only: Vec<String>,

    /// Bail out on the first per-service failure. Off by default —
    /// the orchestrator continues and reports every failure at the
    /// end, which is closer to what an operator running this
    /// against a production restore wants.
    #[arg(long)]
    fail_fast: bool,

    /// Path to a captured `audit_log` SQL dump to load before
    /// rebuilding. Skipped when not provided. The dump is applied
    /// with `psql` against `--database-url`. (Only `audit_log`
    /// content should be in the dump; everything else gets
    /// regenerated by the rebuilders.)
    #[arg(long)]
    audit_log_seed: Option<PathBuf>,

    /// Seconds each step waits, taking no lock, for the event relay to
    /// copy every staged write into audit_log before the step's locked
    /// check decides whether it may wipe (design b046f510). 0 checks
    /// at once.
    #[arg(long, default_value_t = boss_events::outbox::DEFAULT_DRAIN_TIMEOUT_SECS)]
    drain_timeout: u64,
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .compact()
        .init();

    let cli = Cli::parse();

    if let Some(seed) = &cli.audit_log_seed {
        info!(seed = %seed.display(), "loading audit_log seed before rebuild");
        load_audit_log_seed(&cli.database_url, seed)
            .with_context(|| format!("loading {}", seed.display()))?;
    }

    // Replay is exempt from the write-time reference gates
    // (`audit_log.ref_check` — the job_edges trigger et al.). Those
    // gates validate NEW writes against CURRENT state; a rebuild
    // replays history, and history legitimately passes through states
    // that were invalid then and repaired since (the migration
    // rehearsal hit exactly this: a pre-cleanup `backlog_item` value
    // aborted the jobs rebuild on an otherwise chain-verified log).
    // Replay's integrity guards are the hash chain + the rebuild
    // reports, not the live-write gate.
    let pool = PgPoolOptions::new()
        .max_connections(2)
        .after_connect(|conn, _| {
            Box::pin(async move {
                sqlx::Executor::execute(&mut *conn, "SET audit_log.ref_check = 'off'").await?;
                Ok(())
            })
        })
        .connect(&cli.database_url)
        .await
        .with_context(|| "connecting to Postgres")?;

    let drain_timeout = std::time::Duration::from_secs(cli.drain_timeout);
    let mut failures: Vec<(String, String)> = Vec::new();
    let mut total_events: u64 = 0;
    let mut total_skipped: u64 = 0;
    let started_at = Instant::now();

    macro_rules! step {
        ($name:literal, $body:expr) => {
            if cli.skip.iter().any(|s| s == $name) {
                info!(service = $name, "skipped (--skip)");
            } else if !cli.only.is_empty() && !cli.only.iter().any(|s| s == $name) {
                info!(service = $name, "skipped (--only excludes it)");
            } else {
                let t0 = Instant::now();
                // Unlocked and deciding nothing: a relay a poll behind
                // is waited out here rather than refused by the step. A
                // failed read is logged and the step's own locked check
                // still decides — it must not abort the run before the
                // failure summary (review F5).
                if let Err(e) = boss_events::outbox::wait_for_drain(&pool, drain_timeout).await {
                    warn!(service = $name, error = %e, "drain wait failed; the step's locked check decides");
                }
                match $body.await {
                    Ok(report) => {
                        let elapsed_ms = t0.elapsed().as_millis() as u64;
                        let summary = format!("{:?}", report);
                        info!(
                            service = $name,
                            elapsed_ms = elapsed_ms,
                            report = %summary,
                            "rebuilt"
                        );
                        // Best-effort tally of headline counters; not
                        // every report has the same shape so we just
                        // grab two: events_processed + events_skipped.
                        let processed = parse_count(&summary, "events_processed");
                        let skipped = parse_count(&summary, "events_skipped");
                        total_events += processed;
                        total_skipped += skipped;
                    }
                    Err(e) => {
                        error!(service = $name, error = %e, "rebuild failed");
                        failures.push(($name.to_string(), e.to_string()));
                        if cli.fail_fast {
                            anyhow::bail!("aborting after {} failed (fail-fast)", $name);
                        }
                    }
                }
            }
        };
    }

    // Order: catalog before inventory (parts FK dependency); people
    // before accounts (account_team_members → employees FK; surfaced
    // on a fresh-DB docker quickstart where the regen pipeline's
    // prior `--only people` warm-up didn't run). Everything else is
    // independent.
    step!("catalog", boss_catalog::rebuild_catalog(&pool));
    step!("inventory", boss_inventory::rebuild_inventory(&pool));
    // Assets: re-project `assets` + `asset_open_tickets` from the
    // `asset_events` log, serial by serial (upserts, so idempotent on a
    // healthy table). It was `boss assets rebuild-projection`, the one
    // projection no rebuild here covered, reachable only through a CLI
    // verb that defaulted to a local database URL (backlog
    // 05cd6572). A tenant with the equipment module off holds no
    // asset_events and writes zero rows. A row of a retired kind is
    // skipped and counted in `events_skipped`, never a failed step
    // (backlog df6aedb4).
    step!(
        "assets",
        boss_assets::PgAssets::new(pool.clone()).rebuild_projection()
    );
    // products: catalog + finished_product_inventory. Lands after
    // boss_inventory so any FK-shaped cross-references resolve in
    // the canonical dep order even though products is otherwise
    // independent (it doesn't import inventory types).
    // The SubjectKind registry's metadata edits (subject_kind.updated,
    // backlog abc2e9d5) folded onto the migration-seeded rows — before
    // `subjects`, whose identity rows hang off these kinds.
    step!("subject-kinds", async {
        boss_subject_kinds::rebuild::rebuild_subject_kinds(&pool)
            .await
            .map_err(|e| anyhow::anyhow!(e))
    });
    // The Class registry's facts (class.declared / .updated / .retired,
    // backlog 3c6d0186) folded onto the migration-seeded rows — after
    // the kinds every Class hangs off, before `subjects` and every step
    // that reads a taxonomy (catalog and inventory above read no Class).
    step!("classes", async {
        boss_classes::rebuild::rebuild_classes(&pool)
            .await
            .map_err(|e| anyhow::anyhow!(e))
    });
    // Identity table first — reference for the jobs existence gate
    // (subject-model R1; truncate-and-reproject from the log + the
    // locations reference pass).
    step!("subjects", async {
        boss_subject_kinds::subjects::rebuild_subjects(&pool)
            .await
            .map_err(|e| anyhow::anyhow!(e))
    });
    step!("campaigns", async {
        boss_campaigns::rebuild::rebuild_campaigns(&pool)
            .await
            .map_err(|e| anyhow::anyhow!(e))
    });
    step!("customers", async {
        boss_customers::rebuild::rebuild_customers(&pool)
            .await
            .map_err(|e| anyhow::anyhow!(e))
    });
    step!("products", boss_products::rebuild_products(&pool));
    step!("messages", boss_messages::rebuild_messages(&pool));
    step!("people", boss_people::rebuild_people(&pool));
    step!("accounts", boss_accounts::rebuild_accounts(&pool));
    step!("jobs", boss_jobs::rebuild_jobs_and_steps(&pool));
    step!(
        "scheduling",
        boss_jobs::scheduling::rebuild_scheduling(&pool)
    );
    step!(
        "agent-runs",
        boss_jobs::agent_runs::rebuild_agent_runs(&pool)
    );
    step!("shipping", boss_shipping::rebuild_shipping(&pool));
    step!("calendar", boss_calendar::rebuild_calendar(&pool));
    step!("commerce", boss_commerce::rebuild_commerce(&pool));
    step!("content", boss_content::rebuild_content(&pool));

    // Ledger facts: project audit_log → financial_facts via the
    // gl_fact_projection_rules registry. Runs after every upstream
    // service rebuilds because it consumes their replayed events.
    step!("ledger-facts", boss_ledger::rebuild_facts(&pool));

    // Ledger journal entries: project financial_facts →
    // gl_journal_entries via the posting rules. Operator-pinned
    // posting-rule version concerns are real on a live tenant
    // managing real money — but for an audit_log-rooted rebuild
    // (operator just ran rebuild-all), the operator IS pinning
    // by triggering this run. Without this step, an audit_log
    // trim + ledger-facts replay leaves gl_journal_entries
    // out-of-sync with financial_facts.
    step!("ledger-journal", async {
        let report = boss_ledger::rebuild(&pool).await?;
        require_balanced(report)
    });

    // Ledger payroll: project the finance.payroll.run facts back into
    // payroll_runs + payroll_run_lines. Both are pure read-models of
    // the fact (header totals + per-employee lines ride in the
    // payload), so this keeps them from going stale across an audit_log
    // trim — the demo epoch reset runs rebuild-all, which now reproduces
    // payroll exactly from the log instead of leaving prior-cycle rows
    // that collide with the synthesize idempotency key.
    step!("ledger-payroll", boss_ledger::rebuild_payroll(&pool));

    // Ledger tax filings: project the `ledger.tax.filing.created` +
    // `ledger.tax.remitted` events back into `tax_filings`. Same
    // stale-across-epochs class as payroll above — a prior-lap filing
    // that survived the trim was already marked `paid`, so the new
    // lap's remit short-circuited and its liability (2150/2300/2310/
    // 2320) never drained. Rooted in audit_log rather than
    // financial_facts because a non-accruing filing posts no entry and
    // therefore has no fact to rebuild from.
    step!(
        "ledger-tax-filings",
        boss_ledger::rebuild_tax_filings(&pool)
    );

    // Ledger bank settlements: project `ledger.payment.received` +
    // `ledger.payment.settled` back into `bank_settlements`. Third
    // table in the same class. Runs after `commerce` (which TRUNCATEs
    // invoices) so the settlements land against the freshly replayed
    // invoices rather than being detached around them — the old
    // detach/re-attach dance is what orphaned a lap's rows and
    // eventually crashed the settlement sweep.
    step!(
        "ledger-bank-settlements",
        boss_ledger::rebuild_bank_settlements(&pool)
    );

    // Search index LAST: it reads `subjects`, `jobs` and `audit_log`,
    // so it must see every other rebuilder's replayed output rather
    // than whatever those tables held before this run.
    step!("search", boss_search::rebuild_search(&pool));

    // event_facts alongside search, and for the same reason: it is a
    // projection OF audit_log, so it only needs the log itself to be
    // settled. Kept as its own step so a Views problem is diagnosable
    // without re-running the search index, and vice versa.
    step!("event-facts", boss_views::rebuild_event_facts(&pool));

    let total_elapsed_ms = started_at.elapsed().as_millis();
    info!(
        elapsed_ms = total_elapsed_ms,
        events_processed = total_events,
        events_skipped = total_skipped,
        failures = failures.len(),
        "rebuild-all done"
    );
    for (svc, err) in &failures {
        error!(service = %svc, error = %err, "failed");
    }
    if !failures.is_empty() {
        std::process::exit(2);
    }
    Ok(())
}

/// The `ledger-journal` step's verdict: an Ok rebuild whose trial
/// balance does not balance is a FAILED step. The deleted `boss ledger
/// rebuild` verb refused it with this same message; the step that
/// replaced it passed any Ok report until backlog df6aedb4, so an
/// unbalanced journal went green in rebuild-all and in everything that
/// gates on it.
fn require_balanced(report: boss_ledger::RebuildReport) -> Result<boss_ledger::RebuildReport> {
    anyhow::ensure!(
        report.is_balanced(),
        "trial balance mismatch: debits={} credits={}",
        report.total_debits,
        report.total_credits
    );
    Ok(report)
}

/// Crude `Debug`-string scrape — every service's `RebuildReport`
/// uses the same field names, so a substring search picks up the
/// counters without the orchestrator having to know each report's
/// concrete shape.
fn parse_count(debug_str: &str, field: &str) -> u64 {
    // Pattern: `field: 42`
    let needle = format!("{field}: ");
    if let Some(start) = debug_str.find(&needle) {
        let rest = &debug_str[start + needle.len()..];
        let end = rest
            .find(|c: char| !c.is_ascii_digit())
            .unwrap_or(rest.len());
        return rest[..end].parse().unwrap_or(0);
    }
    0
}

fn load_audit_log_seed(database_url: &str, seed_path: &std::path::Path) -> Result<()> {
    use std::process::{Command, Stdio};

    let path_str = seed_path
        .to_str()
        .with_context(|| format!("seed path {} is not UTF-8", seed_path.display()))?;

    // Bundle-import escape hatch: the audit_log_check_refs BEFORE
    // INSERT trigger validates payload subject refs against the
    // projection tables (parts, products, accounts, ...). Those
    // projections are empty at this point — boss-rebuild-all
    // rebuilds them AFTER the audit_log import. Setting
    // `audit_log.ref_check = 'off'` in the session bypasses the
    // trigger for the duration of the psql process. The next
    // rebuild step + every live writer afterward run with the
    // check enabled.
    const ESCAPE_PREFIX: &[u8] = b"SET audit_log.ref_check = 'off';\n";

    let is_gz = path_str.ends_with(".gz");
    let mut psql_cmd = Command::new("psql");
    psql_cmd
        .arg(database_url)
        .arg("--quiet")
        .stdin(Stdio::piped());
    let mut psql = psql_cmd.spawn().with_context(|| "spawning psql")?;

    if is_gz {
        // Stream: prefix + gunzip-stdout → psql-stdin. We own the
        // psql pipe end so the SET statement goes in before the
        // decompressed dump. gunzip is reaped only AFTER the pump
        // returns — the pump owns (and drops) the read end of
        // gunzip's stdout, so by then gunzip has either finished or
        // taken SIGPIPE. Waiting on it while its stdout still had an
        // open, undrained pipe is the order that deadlocks.
        let mut gz = Command::new("gunzip")
            .arg("-c")
            .arg(seed_path)
            .stdout(Stdio::piped())
            .spawn()
            .with_context(|| format!("spawning gunzip for {}", path_str))?;
        let gz_stdout = gz.stdout.take().expect("gunzip stdout");
        let pumped = pump_into_psql(&mut psql, ESCAPE_PREFIX, gz_stdout, path_str);
        let gz_status = gz.wait().with_context(|| "waiting for gunzip")?;
        pumped?;
        if !gz_status.success() {
            anyhow::bail!("gunzip exited {} for {}", gz_status, path_str);
        }
    } else {
        let file =
            std::fs::File::open(seed_path).with_context(|| format!("opening {}", path_str))?;
        pump_into_psql(&mut psql, ESCAPE_PREFIX, file, path_str)?;
    }
    Ok(())
}

/// How often the seed pump logs progress. A multi-GB dump on a slow
/// disk takes long enough that silence reads as a hang.
const SEED_PROGRESS_EVERY: u64 = 256 * 1024 * 1024;

/// Stream `reader` into psql's stdin behind the trigger-disable
/// prefix, then reap psql. Backpressure is expected — on a slow disk
/// psql consumes slower than the reader produces, and the writes
/// block until it catches up; that is throttling, not a hang.
///
/// psql's exit status is the primary diagnosis: when psql dies
/// mid-load, the pipe write surfaces as a broken-pipe error that
/// says nothing about WHY, so a non-zero exit outranks the copy
/// error in the report.
fn pump_into_psql(
    psql: &mut std::process::Child,
    prefix: &[u8],
    mut reader: impl std::io::Read,
    label: &str,
) -> Result<()> {
    use std::io::Write;

    let mut stdin = psql.stdin.take().expect("psql stdin");
    let copied: std::io::Result<u64> = (|| {
        stdin.write_all(prefix)?;
        let mut buf = vec![0u8; 8 * 1024 * 1024];
        let mut total: u64 = 0;
        let mut next_mark = SEED_PROGRESS_EVERY;
        loop {
            let n = reader.read(&mut buf)?;
            if n == 0 {
                break;
            }
            stdin.write_all(&buf[..n])?;
            total += n as u64;
            if total >= next_mark {
                info!(
                    loaded_mib = total / (1024 * 1024),
                    seed = label,
                    "audit_log seed streaming"
                );
                next_mark += SEED_PROGRESS_EVERY;
            }
        }
        Ok(total)
    })();
    // EOF to psql before reaping — waiting on a child while still
    // holding its stdin open is the other order that hangs.
    drop(stdin);
    let status = psql.wait().with_context(|| "waiting for psql")?;
    match (copied, status.success()) {
        (Ok(total), true) => {
            info!(
                loaded_mib = total / (1024 * 1024),
                seed = label,
                "audit_log seed loaded"
            );
            Ok(())
        }
        (_, false) => anyhow::bail!("psql exited {} while loading {}", status, label),
        (Err(e), true) => {
            Err(e).with_context(|| format!("piping {} to psql (psql itself exited 0)", label))
        }
    }
}

#[cfg(test)]
mod ledger_journal_tests {
    use super::*;

    fn report(total_debits: i64, total_credits: i64) -> boss_ledger::RebuildReport {
        boss_ledger::RebuildReport {
            facts_processed: 3,
            entries_dropped: 0,
            entries_created: 3,
            periods_rebuilt: 1,
            total_debits,
            total_credits,
        }
    }

    /// The deleted `boss ledger rebuild` exited non-zero on an
    /// unbalanced trial balance; the `ledger-journal` step that replaced
    /// it passed any Ok report, so an unbalanced rebuild went green
    /// (backlog df6aedb4). The step now fails, naming both totals.
    #[test]
    fn an_unbalanced_trial_balance_fails_the_ledger_journal_step() {
        let err = require_balanced(report(10_000, 9_000)).expect_err("unbalanced must fail");
        let msg = err.to_string();
        assert!(
            msg.contains("trial balance mismatch: debits=10000 credits=9000"),
            "the failure names both totals: {msg}"
        );
    }

    #[test]
    fn a_balanced_trial_balance_passes_its_report_through() {
        let r = report(10_000, 10_000);
        assert_eq!(require_balanced(r.clone()).expect("balanced"), r);
    }
}

#[cfg(test)]
mod seed_pump_tests {
    use super::*;
    use std::process::{Command, Stdio};

    fn consumer(script: &str) -> std::process::Child {
        Command::new("sh")
            .arg("-c")
            .arg(script)
            .stdin(Stdio::piped())
            .spawn()
            .expect("spawn sh consumer")
    }

    /// 16 MiB through a consumer that stalls before draining — far
    /// past any kernel pipe buffer, so the writer must block on
    /// backpressure and then resume. This is the slow-disk shape:
    /// completion, not a hang and not an error.
    #[test]
    fn pump_survives_a_slow_consumer_via_backpressure() {
        let mut child = consumer("sleep 1; cat > /dev/null");
        let data = std::io::Cursor::new(vec![b'x'; 16 * 1024 * 1024]);
        pump_into_psql(&mut child, b"prefix\n", data, "test-slow").expect("pump completes");
    }

    /// The consumer dies early with a distinct status: the report
    /// must carry that exit status — the actual diagnosis — not the
    /// broken-pipe error the writer saw as a consequence.
    #[test]
    fn pump_reports_the_consumer_exit_status_not_the_pipe_error() {
        let mut child = consumer("head -c 4096 > /dev/null; exit 3");
        let data = std::io::Cursor::new(vec![b'x'; 16 * 1024 * 1024]);
        let err =
            pump_into_psql(&mut child, b"prefix\n", data, "test-dead").expect_err("psql died");
        let msg = format!("{err:#}");
        assert!(
            msg.contains("exit status: 3"),
            "want the consumer's exit status in the report, got: {msg}"
        );
    }

    struct FailingReader {
        left: usize,
    }

    impl std::io::Read for FailingReader {
        fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
            if self.left == 0 {
                return Err(std::io::Error::other("seed read failed"));
            }
            let n = self.left.min(buf.len());
            buf[..n].fill(b'x');
            self.left -= n;
            Ok(n)
        }
    }

    /// The reader fails midway while the consumer stays healthy: the
    /// reader's error is the diagnosis (psql exits 0 on the
    /// truncated-but-valid prefix it received).
    #[test]
    fn pump_reports_a_reader_failure_when_the_consumer_is_clean() {
        let mut child = consumer("cat > /dev/null");
        let err = pump_into_psql(
            &mut child,
            b"prefix\n",
            FailingReader { left: 1024 },
            "test-reader",
        )
        .expect_err("reader failed");
        let msg = format!("{err:#}");
        assert!(
            msg.contains("seed read failed"),
            "want the reader error in the report, got: {msg}"
        );
    }
}
