//! `boss-rebuild-all` — replay every per-service projection from
//! `audit_log` in one command.
//!
//! Order matters in exactly one place: `boss-catalog` upserts the
//! shared `parts` table as a side-effect of model replay, and
//! `boss-inventory` references `parts` via the
//! `purchase_order_lines.part_sku` FK. So catalog runs before
//! inventory. Everything else is independent.
//!
//! Each rebuilder is wrapped in its own advisory-locked transaction
//! (`pg_advisory_xact_lock` with a stable per-service key); running
//! them in series, not in parallel, keeps the wipe + replay phase
//! visible to a single observer for any concurrent live writes.
//!
//! Exit code: 0 on full success, non-zero if any service fails.
//! Per-service stats dump as one structured tracing line each.

use std::path::PathBuf;
use std::time::Instant;

use anyhow::{Context, Result};
use clap::Parser;
use sqlx::postgres::PgPoolOptions;
use tracing::{error, info};
use tracing_subscriber::EnvFilter;

#[derive(Parser, Debug)]
#[command(
    name = "boss-rebuild-all",
    about = "Rebuild every projection from audit_log in dependency order",
    version
)]
struct Cli {
    /// Postgres URL. Required — pass via --database-url or set
    /// DATABASE_URL in env (sqlx convention). No config-file
    /// probing; this is a destructive operation, spell it out.
    #[arg(long, env = "DATABASE_URL")]
    database_url: String,

    /// Skip a service. Repeatable. Mostly useful for one-offs:
    /// `--skip catalog` to keep asset_models intact while
    /// rebuilding everything else.
    #[arg(long = "skip")]
    skip: Vec<String>,

    /// Run only the named services. Repeatable. Inverse of
    /// `--skip` — every service NOT listed here is skipped.
    /// Useful when a single audit_log row was just written and the
    /// operator wants to project only that one service (e.g. the
    /// quickstart bootstrap-admin → `--only people`).
    #[arg(long = "only")]
    only: Vec<String>,

    /// Bail out on the first per-service failure. Off by default —
    /// the orchestrator continues and reports every failure at the
    /// end, which is closer to what an operator running this
    /// against a production restore wants.
    #[arg(long)]
    fail_fast: bool,

    /// Path to a captured `audit_log` SQL dump to load before
    /// rebuilding. Skipped when not provided. The dump is applied
    /// with `psql` against `--database-url`. (Only `audit_log`
    /// content should be in the dump; everything else gets
    /// regenerated by the rebuilders.)
    #[arg(long)]
    audit_log_seed: Option<PathBuf>,
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .compact()
        .init();

    let cli = Cli::parse();

    if let Some(seed) = &cli.audit_log_seed {
        info!(seed = %seed.display(), "loading audit_log seed before rebuild");
        load_audit_log_seed(&cli.database_url, seed)
            .with_context(|| format!("loading {}", seed.display()))?;
    }

    let pool = PgPoolOptions::new()
        .max_connections(2)
        .connect(&cli.database_url)
        .await
        .with_context(|| "connecting to Postgres")?;

    let mut failures: Vec<(String, String)> = Vec::new();
    let mut total_events: u64 = 0;
    let mut total_skipped: u64 = 0;
    let started_at = Instant::now();

    macro_rules! step {
        ($name:literal, $body:expr) => {
            if cli.skip.iter().any(|s| s == $name) {
                info!(service = $name, "skipped (--skip)");
            } else if !cli.only.is_empty() && !cli.only.iter().any(|s| s == $name) {
                info!(service = $name, "skipped (--only excludes it)");
            } else {
                let t0 = Instant::now();
                match $body.await {
                    Ok(report) => {
                        let elapsed_ms = t0.elapsed().as_millis() as u64;
                        let summary = format!("{:?}", report);
                        info!(
                            service = $name,
                            elapsed_ms = elapsed_ms,
                            report = %summary,
                            "rebuilt"
                        );
                        // Best-effort tally of headline counters; not
                        // every report has the same shape so we just
                        // grab two: events_processed + events_skipped.
                        let processed = parse_count(&summary, "events_processed");
                        let skipped = parse_count(&summary, "events_skipped");
                        total_events += processed;
                        total_skipped += skipped;
                    }
                    Err(e) => {
                        error!(service = $name, error = %e, "rebuild failed");
                        failures.push(($name.to_string(), e.to_string()));
                        if cli.fail_fast {
                            anyhow::bail!("aborting after {} failed (fail-fast)", $name);
                        }
                    }
                }
            }
        };
    }

    // Order: catalog before inventory (parts FK dependency); people
    // before accounts (account_team_members → employees FK; surfaced
    // on a fresh-DB docker quickstart where the regen pipeline's
    // prior `--only people` warm-up didn't run). Everything else is
    // independent.
    step!("catalog", boss_catalog::rebuild_catalog(&pool));
    step!("inventory", boss_inventory::rebuild_inventory(&pool));
    // products: catalog + finished_product_inventory. Lands after
    // boss_inventory so any FK-shaped cross-references resolve in
    // the canonical dep order even though products is otherwise
    // independent (it doesn't import inventory types).
    step!("products", boss_products::rebuild_products(&pool));
    step!("messages", boss_messages::rebuild_messages(&pool));
    step!("people", boss_people::rebuild_people(&pool));
    step!("accounts", boss_accounts::rebuild_accounts(&pool));
    step!("jobs", boss_jobs::rebuild_jobs_and_steps(&pool));
    step!(
        "scheduling",
        boss_jobs::scheduling::rebuild_scheduling(&pool)
    );
    step!("shipping", boss_shipping::rebuild_shipping(&pool));
    step!("calendar", boss_calendar::rebuild_calendar(&pool));
    step!("commerce", boss_commerce::rebuild_commerce(&pool));
    step!("content", boss_content::rebuild_content(&pool));

    // Ledger facts: project audit_log → financial_facts via the
    // gl_fact_projection_rules registry. Runs after every upstream
    // service rebuilds because it consumes their replayed events.
    step!("ledger-facts", boss_ledger::rebuild_facts(&pool));

    // Ledger journal entries: project financial_facts →
    // gl_journal_entries via the posting rules. Operator-pinned
    // posting-rule version concerns are real on a live tenant
    // managing real money — but for an audit_log-rooted rebuild
    // (operator just ran rebuild-all), the operator IS pinning
    // by triggering this run. Without this step, an audit_log
    // trim + ledger-facts replay leaves gl_journal_entries
    // out-of-sync with financial_facts.
    step!("ledger-journal", boss_ledger::rebuild(&pool));

    let total_elapsed_ms = started_at.elapsed().as_millis();
    info!(
        elapsed_ms = total_elapsed_ms,
        events_processed = total_events,
        events_skipped = total_skipped,
        failures = failures.len(),
        "rebuild-all done"
    );
    for (svc, err) in &failures {
        error!(service = %svc, error = %err, "failed");
    }
    if !failures.is_empty() {
        std::process::exit(2);
    }
    Ok(())
}

/// Crude `Debug`-string scrape — every service's `RebuildReport`
/// uses the same field names, so a substring search picks up the
/// counters without the orchestrator having to know each report's
/// concrete shape.
fn parse_count(debug_str: &str, field: &str) -> u64 {
    // Pattern: `field: 42`
    let needle = format!("{field}: ");
    if let Some(start) = debug_str.find(&needle) {
        let rest = &debug_str[start + needle.len()..];
        let end = rest
            .find(|c: char| !c.is_ascii_digit())
            .unwrap_or(rest.len());
        return rest[..end].parse().unwrap_or(0);
    }
    0
}

fn load_audit_log_seed(database_url: &str, seed_path: &std::path::Path) -> Result<()> {
    use std::io::{Read, Write};
    use std::process::{Command, Stdio};

    let path_str = seed_path
        .to_str()
        .with_context(|| format!("seed path {} is not UTF-8", seed_path.display()))?;

    // Bundle-import escape hatch: the audit_log_check_refs BEFORE
    // INSERT trigger validates payload subject refs against the
    // projection tables (parts, products, accounts, ...). Those
    // projections are empty at this point — boss-rebuild-all
    // rebuilds them AFTER the audit_log import. Setting
    // `audit_log.ref_check = 'off'` in the session bypasses the
    // trigger for the duration of the psql process. The next
    // rebuild step + every live writer afterward run with the
    // check enabled.
    const ESCAPE_PREFIX: &[u8] = b"SET audit_log.ref_check = 'off';\n";

    let is_gz = path_str.ends_with(".gz");
    let mut psql = Command::new("psql");
    psql.arg(database_url).arg("--quiet").stdin(Stdio::piped());

    if is_gz {
        // Stream: prefix + gunzip-stdout → psql-stdin. We own the
        // psql pipe end so the SET statement goes in before the
        // decompressed dump.
        let mut gz = Command::new("gunzip")
            .arg("-c")
            .arg(seed_path)
            .stdout(Stdio::piped())
            .spawn()
            .with_context(|| format!("spawning gunzip for {}", path_str))?;
        let mut gz_stdout = gz.stdout.take().expect("gunzip stdout");
        let mut child = psql.spawn().with_context(|| "spawning psql")?;
        let mut stdin = child.stdin.take().expect("psql stdin");
        stdin
            .write_all(ESCAPE_PREFIX)
            .with_context(|| "writing trigger-disable prefix to psql")?;
        std::io::copy(&mut gz_stdout, &mut stdin).with_context(|| "piping gunzip to psql")?;
        drop(stdin);
        let psql_status = child.wait().with_context(|| "waiting for psql")?;
        let gz_status = gz.wait().with_context(|| "waiting for gunzip")?;
        if !gz_status.success() {
            anyhow::bail!("gunzip exited {}", gz_status);
        }
        if !psql_status.success() {
            anyhow::bail!("psql exited {}", psql_status);
        }
    } else {
        let mut child = psql.spawn().with_context(|| "spawning psql")?;
        let mut file =
            std::fs::File::open(seed_path).with_context(|| format!("opening {}", path_str))?;
        let mut stdin = child.stdin.take().expect("psql stdin");
        stdin
            .write_all(ESCAPE_PREFIX)
            .with_context(|| "writing trigger-disable prefix to psql")?;
        std::io::copy(&mut file, &mut stdin).with_context(|| "piping seed to psql")?;
        // Force EOF before waiting.
        drop(stdin);
        let mut buf = Vec::new();
        let _ = file.read_to_end(&mut buf);
        let status = child.wait().with_context(|| "waiting for psql")?;
        if !status.success() {
            anyhow::bail!("psql exited {}", status);
        }
    }
    Ok(())
}
