# Tax kind → liability GL account-code mapping. Loaded once at first
# call by `boss_ledger::rules::liability_account_for()`. Same shape
# as `revenue_accounts.toml` (D3) — tenant overrides via
# `BOSS_LEDGER_TAX_LIABILITY_ACCOUNTS_TOML` env var.
#
# The ledger's posting rules cross-check this mapping at
# `finance.tax.{accrued,remitted}` evaluation time — both the
# sim-bridge that emits the snapshot and the ledger that posts
# the JE need to agree on which account a given tax kind hits.
# Both sides resolve through this file via `liability_account_for()`.

"sales"       = "2300"
"income"      = "2310"
"payroll_941" = "2150"
"payroll_940" = "2150"
