//! Rebuild the catalog projections from `audit_log`.
//!
//! Seventh projection rebuilder in the event-canonical arc (after
//! messages / jobs / inventory / accounts / shipping / people).
//! See `docs/design/projection-rebuilders.md`.
//!
//! Catalog owns 9 tables: `asset_models` plus 8 satellites
//! (wavelengths, spot_sizes, use_cases, failure_modes,
//! pm_checklist, spare_parts, consumables, documents). The
//! `parts` table is shared with boss-inventory (purchase orders,
//! inventory items reference it) so we don't wipe it — instead
//! the model-event replay UPSERTs parts as a side-effect of
//! re-inserting spare_parts and consumables.
//!
//! State events consumed:
//! - `kb.model.created` / `.updated` — full `AssetModel`
//!   payload (parent row + all 8 satellite vectors).
//! - `kb.model.deleted` — `{sku, deleted_at}`.

use boss_events::replay::{Applied, replay_projection};
use sqlx::PgPool;
use tracing::warn;

use crate::postgres::{delete_satellites, insert_satellites, upsert_model_row};
use crate::types::AssetModel;

const REBUILD_LOCK_KEY: i64 = boss_core::rebuild::lock_key("catalog");

#[derive(Debug, thiserror::Error)]
pub enum RebuildError {
    #[error("storage: {0}")]
    Storage(String),
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RebuildReport {
    pub events_processed: u64,
    pub events_skipped: u64,
    pub models_upserted: u64,
    pub models_deleted: u64,
}

pub async fn rebuild_catalog(pool: &PgPool) -> Result<RebuildReport, RebuildError> {
    let mut report = RebuildReport::default();

    // No table-wipe: this rebuilder is UPSERT-only. A
    // DELETE-then-replay would blow up on the FK from
    // `assets(sku) → asset_models(sku)`.
    //
    // Why UPSERT-only is correct: catalog rows are *data-seeded*
    // (from `examples/<tenant>/seeds/`), not generated by the sim,
    // so the rebuild path never needs to clear them. Replay of
    // `kb.model.created/updated` events still UPSERTs the parent
    // row + satellites; deletes propagate via `kb.model.deleted`
    // by SKU below. The only behavior change vs. the wipe pattern:
    // a row that exists in the projection but has NO event in the
    // current audit_log slice will persist — and that's the right
    // shape, because the seed events are deliberately retained
    // outside the trim window for exactly that reason. Wiping
    // would corrupt the projection rather than rebuild it.
    //
    // Satellite tables: cleared per-SKU inside the upsert branch
    // below (`delete_satellites` runs scoped to the model's SKU,
    // not table-wide), so the per-event "replace satellites
    // wholesale" semantics still hold.
    let stats = replay_projection(
        pool,
        REBUILD_LOCK_KEY,
        &[],
        "kind LIKE 'kb.model.%'",
        async |conn, ev| {
            match ev.kind.as_str() {
                "kb.model.created" | "kb.model.updated" => {
                    let model: AssetModel = match serde_json::from_value(ev.payload.clone()) {
                        Ok(m) => m,
                        Err(e) => {
                            warn!(
                                event_id = ev.audit_id,
                                kind = %ev.kind,
                                error = %e,
                                "skipping kb.model event with non-AssetModel payload \
                                 (likely pre-enrichment id-only)"
                            );
                            return Ok(Applied::Skipped);
                        }
                    };
                    upsert_model_row(&mut *conn, &model, ev.ts)
                        .await
                        .map_err(|e| e.to_string())?;
                    // Replace satellites wholesale per upsert event.
                    delete_satellites(&mut *conn, &model.sku)
                        .await
                        .map_err(|e| e.to_string())?;
                    insert_satellites(&mut *conn, &model)
                        .await
                        .map_err(|e| e.to_string())?;
                    report.models_upserted += 1;
                    Ok(Applied::Yes)
                }
                "kb.model.deleted" => {
                    let sku: Option<String> = ev
                        .payload
                        .get("sku")
                        .and_then(|v| v.as_str())
                        .map(String::from);
                    if let Some(sku) = sku {
                        let n = sqlx::query("DELETE FROM asset_models WHERE sku = $1")
                            .bind(&sku)
                            .execute(&mut *conn)
                            .await
                            .map_err(|e| e.to_string())?
                            .rows_affected();
                        if n > 0 {
                            report.models_deleted += 1;
                            Ok(Applied::Yes)
                        } else {
                            Ok(Applied::Skipped)
                        }
                    } else {
                        Ok(Applied::Skipped)
                    }
                }
                other => {
                    warn!(event_id = ev.audit_id, kind = %other, "unknown kb.* event kind");
                    Ok(Applied::Skipped)
                }
            }
        },
    )
    .await
    .map_err(RebuildError::Storage)?;

    report.events_processed = stats.processed;
    report.events_skipped = stats.skipped;
    Ok(report)
}
